# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b5fa0de521ec25d7032ff51fd20b4a2bcfe13c8a7aa2b9a827b91ef9bac12ad609f2bf56bdb1295d37ed444b576fd509d7c5ed83c7d48acbf23e88baf4a02aa8

test:
  secret_key_base: c61a8fce533fb6e4e9d1f56e4f523bfd796fb481307dc5f206a19c5a97fec02a9eecf1aa6e42b7598e46421ec53c4f9a7d426b99bca21cd1aea9629ab690d34c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
